import{a as S,S as q,i as l}from"./assets/vendor-Dy2ZTtfi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const M="50865810-65dd075ae8c3362400e1c5e2f";let $=15;async function m(r,e){return(await S("https://pixabay.com/api/",{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:$,page:e}})).data}const y=document.querySelector(".gallery"),u=document.querySelector(".loader"),g=document.querySelector(".btn-load");function b(r){const e=r.map(({webformatURL:a,largeImageURL:s,tags:t,likes:o,views:n,comments:w,downloads:P})=>`
      <li class="list-item">
      <a href="${s}">
      <img src="${a}" alt="${t}" width="360"/>
      </a>
      <div class="info">
            <p>Likes ${o}</p>
            <p>Views ${n}</p>
            <p>Comments ${w}</p>
            <p>Downloads ${P}</p>
        </div>
        
      </li>  
        `).join("");y.insertAdjacentHTML("beforeend",e),E.refresh()}function H(){y.innerHTML=""}function L(){u&&u.classList.remove("hidden")}function h(){u&&u.classList.add("hidden")}const E=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function v(){g.classList.remove("hidden")}function p(){g.classList.add("hidden")}const d=document.querySelector(".input-text"),O=document.querySelector(".form"),x=document.querySelector(".btn-load");let i=1,f=15,c="";O.addEventListener("submit",B);x.addEventListener("click",D);async function B(r){if(r.preventDefault(),c=d.value.trim(),i=1,H(),p(),c===""){l.show({title:"Warning",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),d.value="";return}L();try{const e=await m(c,i);if(e.hits.length===0){p(),l.show({title:"Hey",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}b(e.hits);const a=Math.ceil(e.totalHits/f),s=e.hits.length*i;console.log(s,e.totalHits),i<a?v():l.show({title:"!",color:"blue",position:"topRight",message:"We are sorry, but you have reached the end of search results"})}catch(e){console.error("Fetch error:",e)}finally{h(),d.value=""}}async function D(r){r.preventDefault(),i+=1;try{L();const e=await m(c,i);b(e.hits),h();const s=document.querySelector(".gallery").firstElementChild,{height:t}=s.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"});const o=Math.ceil(e.totalHits/f),n=i*f;if(console.log(n,e.totalHits),i>=o){h(),l.show({title:"!",color:"blue",position:"topRight",message:"We are sorry, but you have reached the end of search results"}),p();return}v()}catch(e){console.error("Fetch error:",e)}}
//# sourceMappingURL=index.js.map
