import{a as w,S,i as c}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q="50865810-65dd075ae8c3362400e1c5e2f";let P=15;async function p(i,t){return(await w("https://pixabay.com/api/",{params:{key:q,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:t}})).data}const f=document.querySelector(".gallery"),u=document.querySelector(".loader"),m=document.querySelector(".btn-load");function y(i){const t=i.map(({webformatURL:r,largeImageURL:s,tags:e,likes:o,views:a,comments:L,downloads:v})=>`
      <li class="list-item">
      <a href="${s}">
      <img src="${r}" alt="${e}" width="360"/>
      </a>
      <div class="info">
            <p>Likes ${o}</p>
            <p>Views ${a}</p>
            <p>Comments ${L}</p>
            <p>Downloads ${v}</p>
        </div>
        
      </li>  
        `).join("");f.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){f.innerHTML=""}function g(){u&&u.classList.remove("hidden")}function h(){u&&u.classList.add("hidden")}const E=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function b(){m.classList.remove("hidden")}function M(){m.classList.add("hidden")}const d=document.querySelector(".input-text"),H=document.querySelector(".form"),O=document.querySelector(".btn-load");let n=1,x=15,l="";H.addEventListener("submit",B);O.addEventListener("click",D);async function B(i){if(i.preventDefault(),l=d.value.trim(),n=1,$(),l===""){c.show({title:"Warning",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),d.value="";return}g();try{const t=await p(l,n);if(t.hits.length===0){c.show({title:"Hey",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits);const r=t.hits.length*n;r<t.totalHits&&r!=0?b():c.show({title:"!",color:"blue",position:"topRight",message:"We are sorry, but you have reached the end of search results"})}catch(t){console.error("Fetch error:",t)}finally{h(),d.value=""}}async function D(i){i.preventDefault(),n+=1;const t=await p(l,n);g(),y(t.hits),h();const r=document.querySelector(".list-item"),{height:s}=r.getBoundingClientRect();if(window.scrollBy({top:s*2,left:100,behavior:"smooth"}),b(),n*x>=t.totalHits){h(),c.show({title:"!",color:"blue",position:"topRight",message:"We are sorry, but you have reached the end of search results"}),M();return}}
//# sourceMappingURL=index.js.map
