import{a as v,S,i as l}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="50865810-65dd075ae8c3362400e1c5e2f";let P=15;async function p(r,t){return(await v("https://pixabay.com/api/",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:t}})).data}const f=document.querySelector(".gallery"),u=document.querySelector(".loader"),m=document.querySelector(".btn-load");function y(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:a,comments:L,downloads:w})=>`
      <li class="list-item">
      <a href="${s}">
      <img src="${i}" alt="${e}" width="360"/>
      </a>
      <div class="info">
            <p>Likes ${o}</p>
            <p>Views ${a}</p>
            <p>Comments ${L}</p>
            <p>Downloads ${w}</p>
        </div>
        
      </li>  
        `).join("");f.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){f.innerHTML=""}function g(){u&&u.classList.remove("hidden")}function d(){u&&u.classList.add("hidden")}const E=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function b(){m.classList.remove("hidden")}function M(){m.classList.add("hidden")}const h=document.querySelector(".input-text"),H=document.querySelector(".form"),O=document.querySelector(".btn-load");let n=1,x=15,c="";H.addEventListener("submit",B);O.addEventListener("click",D);async function B(r){if(r.preventDefault(),c=h.value.trim(),n=1,$(),g(),c===""){l.show({title:"Warning",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}try{const t=await p(c,n);if(t.hits.length===0){l.show({title:"Hey",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits),t.hits.length*n<t.totalHits?b():l.show({title:"!",color:"blue",position:"topRight",message:"We are sorry, but you have reached the end of search results"})}catch(t){console.error("Fetch error:",t)}finally{d(),h.value=""}}async function D(r){r.preventDefault(),n+=1;const t=await p(c,n);g(),y(t.hits),d();const i=document.querySelector(".list-item"),{height:s}=i.getBoundingClientRect();if(window.scrollBy({top:s*2,left:100,behavior:"smooth"}),b(),n*x>=t.totalHits){d(),l.show({title:"!",color:"blue",position:"topRight",message:"We are sorry, but you have reached the end of search results"}),M();return}}
//# sourceMappingURL=index.js.map
